- project:
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python35-jobs-nonvoting
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
