#!/bin/bash
#
# Copyright 2019 vishnu <vishnukb@acceleronlabs.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
# Author        : vishnu
# FileName      : database


#This function creates the masakari database
#
mdc_create_masakari_database() {
	#FNAME="create_masakari_database"
	MYSQL_HOST="localhost"
	db=$1
	echo_console "++--  database bulding masakari"
	result=0
	echo -e "${CYAN}++--  sudo mysql -u$MYSQL_USER -p****** -h$MYSQL_HOST -e \"DROP DATABASE IF EXISTS $db;\"${RESET}"
	sudo mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -h$MYSQL_HOST -e "DROP DATABASE IF EXISTS $db;" ; result=` expr $result + $? `
	
	echo -e "${CYAN}++--  sudo mysql -u$MYSQL_USER -p****** -h$MYSQL_HOST -e \"CREATE DATABASE $db CHARACTER SET utf8;\"${RESET}"
	sudo mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -h$MYSQL_HOST -e "CREATE DATABASE $db CHARACTER SET utf8;" ; result=` expr $result + $? `
	
	echo -e "${CYAN}++--  sudo mysql -u$MYSQL_USER -p****** -h$MYSQL_HOST -e \"GRANT ALL PRIVILEGES ON $db.* TO '$db'@'localhost' IDENTIFIED BY '$DB_PASSWORD'\"${RESET}"
	sudo mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -h$MYSQL_HOST -e "GRANT ALL PRIVILEGES ON $db.* TO '$db'@'localhost' IDENTIFIED BY '$DB_PASSWORD'" ; result=` expr $result + $? `
	
	echo -e "${CYAN}++--  sudo mysql -u$MYSQL_USER -p****** -h$MYSQL_HOST -e \"GRANT ALL PRIVILEGES ON $db.* TO '$db'@'%' IDENTIFIED BY '$DB_PASSWORD'\"${RESET}"
	sudo mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -h$MYSQL_HOST -e "GRANT ALL PRIVILEGES ON $db.* TO '$db'@'%' IDENTIFIED BY '$DB_PASSWORD'" ; result=` expr $result + $? `
	return $result
}


