#!/bin/bash
#
# Copyright 2019 vishnu <vishnukb@acceleronlabs.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
# Author        : vishnu
# FileName      : include
# Description   : to include necessary macros and apis

#Directories
TOP_DIR=$(cd $(dirname "$0") && pwd)
MASAKARI_DIR="$TOP_DIR/masakari"
MASAKARIMONITOR_DIR="$TOP_DIR/masakari-monitors"
ETC_DIR="$TOP_DIR/etc"
LOGDIR="$TOP_DIR/log"
LOGFILE="${LOGDIR}/masakari.log"
LOCAL_CONF="$TOP_DIR/local.conf"
MASAKARI_CONF="/etc/masakari"
MASAKARIMONITOR_CONF="/etc/masakarimonitors"
LIB_SERVICE_DIR="/lib/systemd/system"
SERVICE_DIR="/etc/systemd/system"
MULTI_USER="/etc/systemd/system/multi-user.target.wants"

#Colors
RED=`tput setaf 1`
GREEN=`tput setaf 2`
CYAN=`tput setaf 6`
YELLOW=`tput setaf 3`
RESET=`tput sgr0`

# Filename to use in the script
FNAME="${YELLOW}mdcMasakari${RESET}"

#This function outputs the console print
#Argument
#	$1 : Message
function echo_console {
	echo "`date +'%Y-%m-%d %H:%M:%S'`::${FNAME}::${HOST_NAME}::$1" 
}

#This function outputs the error print
#Argument
#	$1 : Message
function echo_error {
	echo "${RED}`seq -s'#' 0 $(tput cols) | tr -d '[:digit:]'`"
	echo "ERROR MSG: $1 "
	echo ":-( :-( :-("
	echo "Script exit"
	echo "Before running masakari.sh run uninstall.sh"
	echo "& make sure that the database (if created) is removed."
	echo "`seq -s'#' 0 $(tput cols) | tr -d '[:digit:]'`${RESET}"
}

#This function outputs the success print
#
function echo_success {
	echo "${GREEN}`seq -s'#' 0 $(tput cols) | tr -d '[:digit:]'`"
	echo "${GREEN}mdcMasakari"
	echo "Success :-)"
	echo "Verify Masakari:-"
	echo -e ''$_{1..20}'\b+'
	echo "* In controller add the create segment and add host (mininum two compute host)"
	echo "	$ . admin-openrc"
	echo "	$ masakari segment-create --name failover --recovery-method auto --service-type compute --description instance_ha"
	echo "* Create an instance in host that is going to down."
	echo "* Verify that the instance is in the correct host."
        echo "* Poweroff the host that contain instance."
	echo "* After a few minutes the instance is move to the reserved host"
	echo "`seq -s'#' 0 $(tput cols) | tr -d '[:digit:]'`${RESET}"

}

function record {
	choice=$1
	case $choice in
	start)
		touch .record
		echo "=============mdcMasakari Install Record=============" > .record
		;;
	end)
		echo "=============END=============" >> .record
		;;
	substart)
		echo "++--  $2  --++" >> .record
		;;
	subend)
		echo "++--  end  --++" >> .record
		;;
	content)
		echo "$2" >> .record
		;;
	*)
		;;
	esac
}
