---
other:
  - |
    Adopt oslo-config-generator to generate sample config files.
    New config options from masakari code should register with
    masakari/conf/opts.py. A deprecated option should add a
    deprecated group even if it didn't alter its group, otherwise
    the deprecated group will use 'DEFAULT' by default.
